# Generated by Django 4.2.5 on 2023-10-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Dell', 'Dell'), ('Apple', 'Apple'), ('Asus', 'Asus'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('MSI', 'MSI')], max_length=255, null=True),
        ),
    ]
