# Generated by Django 4.2.5 on 2023-10-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hard_drive',
            new_name='hard_drive_type',
        ),
        migrations.AddField(
            model_name='product',
            name='hard_drive_capacity',
            field=models.CharField(blank=True, choices=[('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('4TB', '4TB'), ('8TB', '8TB'), ('16TB', '16TB')], max_length=255, null=True),
        ),
    ]
